version: "3.9"

services:
  ipfs:
    image: ipfs/kubo:v0.30.0
    ports:
      - "5001:5001" # API
    volumes:
      - ipfs-data:/data/ipfs

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  graph-node:
    image: graphprotocol/graph-node:v0.35.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8000:8000" # GraphQL HTTP
      - "8001:8001" # GraphQL WebSocket
      - "8020:8020" # Admin JSON-RPC
      - "8030:8030" # Index Node JSON-RPC
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      ipfs: 'ipfs:5001'
      # Connect to local Anvil fork
      ethereum: 'mainnet:http://host.docker.internal:8545'
      RUST_LOG: info

volumes:
  ipfs-data: {}
  postgres-data: {}


